'use strict';
const entry=document.getElementById('entry-lab');
const oldRBX='0x1122334455667788';
const instructions=['push rbx','pushfq','mov rbx, 3F8AB3AF09240D32h','not bl','mov rbx, 418D6190ECBC5713h','mov rbx, [rsp+8]','mov qword ptr [rsp+8], 26D3A714h','push qword ptr [rsp]','popfq','lea rsp, [rsp+8]','call entry_initializer'];
const explanations=[
['At function entry','RSP points at the caller’s return address. Save this address as entry_rsp. entry_rsp is taken as 0x1000 for clear arithmetic.','RSP → memory at 0x1000'],
['Reserve eight bytes, then save RBX','RSP changes from 0x1000 to 0x0FF8. The old RBX value is written into those eight bytes. RBX itself does not change.','RBX → [0x0FF8] · RSP ↓ 8 bytes'],
['Save the flags','PUSHFQ moves RSP down another eight bytes and stores the saved flag value. It does not save the other CPU registers.','RFLAGS → [0x0FF0] · RSP ↓ 8 bytes'],
['Overwrite the working register','RBX receives a constant. Its original value remains in the stack slot at 0x0FF8. The stack pointer does not move.','constant → RBX · RSP unchanged'],
['Flip only the low byte','NOT BL changes 0x32 into 0xCD. Other RBX bytes stay unchanged. NOT does not change the flags. This result is overwritten by the next instruction.','BL: 0x32 → 0xCD'],
['Overwrite RBX again','The second MOV replaces the whole register. The earlier constant and NOT result no longer contribute to RBX’s value.','new constant → RBX'],
['Read the saved value back','RSP is 0x0FF0, so RSP+8 is 0x0FF8. MOV reads old RBX from that slot. It does not pop it or change RSP.','[RSP+8] = [0x0FF8] → RBX'],
['Reuse the saved-register slot','Old RBX is now back in the register. The same memory slot is overwritten with the entry token 0x26D3A714.','entry token → [0x0FF8]'],
['Duplicate the saved flags','The source [RSP] is read using the old RSP, 0x0FF0. PUSH then moves RSP to 0x0FE8 and stores a copy of that value there.','[0x0FF0] → [0x0FE8] · RSP ↓ 8 bytes'],
['Load the duplicate into flags','POPFQ consumes the value at 0x0FE8, restoring permitted flag bits. RSP advances to 0x0FF0. The bytes at 0x0FE8 are not erased.','[0x0FE8] → RFLAGS · RSP ↑ 8 bytes'],
['Skip the original flags slot','LEA calculates RSP+8 and puts that address into RSP. It does not read the flags slot. The token is now at the top of the stack.','RSP: 0x0FF0 → 0x0FF8'],
['Enter the initializer','CALL pushes its next-instruction address into 0x0FF0 and transfers to the initializer at RVA 0x1D595. The entry token remains at RSP+8.','return VA → [0x0FF0] · RIP → initializer']
];
function states(){let x={rsp:0x1000,rbx:oldRBX,flags:'saved flags',rip:'entry stub',mem:{4096:'caller return'},write:null,changed:[]};const list=[structuredClone(x)];function save(changed,write=null){x.changed=changed;x.write=write;list.push(structuredClone(x))}
x.rsp-=8;x.mem[x.rsp]=oldRBX;save(['rsp'],x.rsp);
x.rsp-=8;x.mem[x.rsp]='saved flags';save(['rsp'],x.rsp);
x.rbx='0x3F8AB3AF09240D32';save(['rbx']);
x.rbx='0x3F8AB3AF09240DCD';save(['rbx']);
x.rbx='0x418D6190ECBC5713';save(['rbx']);
x.rbx=x.mem[x.rsp+8];save(['rbx']);
x.mem[x.rsp+8]='0x26D3A714 · token';save([],x.rsp+8);
const flags=x.mem[x.rsp];x.rsp-=8;x.mem[x.rsp]=flags;save(['rsp'],x.rsp);
x.flags=x.mem[x.rsp];x.rsp+=8;save(['rsp','flags']);
x.rsp+=8;save(['rsp']);
x.rsp-=8;x.mem[x.rsp]='image base + 0x27FB31';x.rip='image base + 0x1D595';save(['rsp','rip'],x.rsp);return list}
const snapshots=states();let step=0;const hex=n=>'0x'+n.toString(16).toUpperCase().padStart(4,'0');
entry.querySelector('.assembly-list').innerHTML='<div class="panel-label">EXECUTED INSTRUCTION → EFFECT</div>'+instructions.map((v,i)=>`<button class="asm-row" data-step="${i+1}"><span class="line-no">${String(i+1).padStart(2,'0')}</span><span>${v}</span><span class="arrow" aria-hidden="true">→</span></button>`).join('');
function renderEntry(){const s=snapshots[step];entry.querySelector('.step-label').textContent=step===0?'Before the first instruction':`After instruction ${step} / ${instructions.length}`;entry.querySelectorAll('.asm-row').forEach(b=>{const active=Number(b.dataset.step)===step;b.classList.toggle('active',active);b.setAttribute('aria-pressed',String(active))});entry.querySelector('[data-action="back"]').disabled=step===0;entry.querySelector('[data-action="next"]').disabled=step===instructions.length;
entry.querySelector('.registers').innerHTML=[['rsp','RSP',hex(s.rsp)],['rbx','RBX',s.rbx],['flags','RFLAGS',s.flags],['rip','RIP',s.rip]].map(([key,label,value])=>`<div class="reg ${s.changed.includes(key)?'changed':''}"><span>${label}</span><span>${value}</span></div>`).join('');
entry.querySelector('.stack').innerHTML=[0x1000,0xff8,0xff0,0xfe8].map(a=>`<div class="stack-row ${s.rsp===a?'pointed':''} ${s.write===a?'written':''}"><span class="slot-address">${hex(a)}${s.rsp===a?'<small>RSP →</small>':''}</span><span class="slot-value">${s.mem[a]||'not used yet'}<small>${a===0x1000?'entry_rsp':`entry_rsp − ${0x1000-a} bytes`}${a<s.rsp&&s.mem[a]?' · below current RSP':''}</small></span></div>`).join('');
const e=explanations[step];entry.querySelector('.transfer-arrow').textContent=e[2];entry.querySelector('.step-explanation').innerHTML=`<strong>${e[0]}.</strong> ${e[1]}`}
entry.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.step)step=Number(b.dataset.step);if(b.dataset.action==='next')step=Math.min(step+1,instructions.length);if(b.dataset.action==='back')step=Math.max(step-1,0);if(b.dataset.action==='reset')step=0;renderEntry()});renderEntry();
const exits=[['Before RET','Restoration is complete; the transfer has not executed. The top stack qword is the native destination, not the caller’s address.','RIP = base + 0x21FAA<br>RSP = entry_rsp − 8<br>[RSP] = base + 0x26C8<br>[RSP+8] = caller_return<br>RCX = base + 0x4000<br>EAX = 1 (observed)','POST-VM TRANSFER READY'],['At the puts thunk','RET has consumed the destination and advanced RSP by eight. Capture the post-VM native registers here, before the JMP runs. puts has not executed.','RIP = base + 0x26C8<br>RSP = entry_rsp<br>[RSP] = caller_return<br>RCX → "Hello DALI !"<br>EAX = 1 (not a result of puts)','VM REGION HAS FINISHED'],['At the caller in main','puts has run and returned to the original caller. Read EAX before the waiting XOR clears it. vmp_target is void, so it still has no defined C return value.','RIP = base + 0x274E<br>RSP = entry_rsp + 8<br>EAX = 0 (observed after puts)<br>Next: xor eax, eax','FUNCTION INVOCATION HAS FINISHED']];
function renderExit(i){const x=exits[i];document.querySelectorAll('[data-exit]').forEach(b=>{b.classList.toggle('active',+b.dataset.exit===i);b.setAttribute('aria-pressed',String(+b.dataset.exit===i))});document.querySelector('.exit-view').innerHTML=`<div><span class="boundary-label">${x[3]}</span><h4>${x[0]}</h4><p>${x[1]}</p></div><div class="exit-values">${x[2]}</div>`}document.querySelectorAll('[data-exit]').forEach(b=>b.onclick=()=>renderExit(+b.dataset.exit));renderExit(0);
const loads=[['21E9D · mov r8, [rsp+rax-4032A19Fh]','RSP = frame_base; RAX = 0x4032A1A7','0x4032A1A7 − 0x4032A19F = 8','[frame_base + 8] → R8','MOV reads eight bytes from this slot. It does not move RSP.'],['21F16 · mov rbp, [rsp+rcx*4-3FE68h]','RSP = frame_base + 8; RCX = 0xFFA6','0xFFA6 × 4 − 0x3FE68 = 0x30','[frame_base + 8 + 0x30] → RBP','The final offset is 0x38, not 0x30, because an earlier POP advanced RSP.'],['21F63 · mov rcx, [rsp+rcx*4-3FE44h]','RSP = frame_base; RCX = 0xFFA7','0xFFA7 × 4 − 0x3FE44 = 0x58','[frame_base + 0x58] → RCX','The old RCX calculates the address. Then MOV replaces RCX with the loaded string pointer.']];
function renderLoad(i){document.querySelectorAll('[data-load]').forEach(b=>{b.classList.toggle('active',+b.dataset.load===i);b.setAttribute('aria-pressed',String(+b.dataset.load===i))});const x=loads[i];document.querySelector('.address-view').innerHTML=x.slice(0,4).map((s,j)=>`<div class="equation"><span>${j===0?'':'↓'}</span><div>${s}</div></div>`).join('')+`<p>${x[4]}</p>`}document.querySelectorAll('[data-load]').forEach(b=>b.onclick=()=>renderLoad(+b.dataset.load));renderLoad(0);
const theme=document.getElementById('theme-toggle');if(theme){theme.onclick=()=>{const dark=document.documentElement.dataset.mode!=='dark';document.documentElement.dataset.mode=dark?'dark':'light';theme.textContent=dark?'Light':'Dark'}};
document.querySelectorAll('pre').forEach(pre=>{const code=pre.querySelector('code');if(!code)return;const button=document.createElement('button');button.className='copy-code';button.textContent='Copy';button.onclick=async()=>{try{await navigator.clipboard.writeText(code.textContent);button.textContent='Copied'}catch{const range=document.createRange();range.selectNodeContents(code);getSelection().removeAllRanges();getSelection().addRange(range);button.textContent='Selected — Ctrl+C'}setTimeout(()=>button.textContent='Copy',2000)};pre.prepend(button)});
